const contractAddress = "0xF8f07d298cfC315149Abf928cDA2A60C2b453ACf"; // Replace with your own contract address
const chain = 'goerli'; // goerli, polygon, or ethereum

const welcome_h1 = "Welcome to the Cryptoocean!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'Cool Humpbacks series is an NFT collection created by a young novice programmer and Pixel Art lover as a form of self-expression and educational introduction into Non-fungible Tokens. Those nutty hefty whales are actually very fascinating not only because they are considered to be one of the largest mammals on Earth. They are also a zoomorphic representation of individuals that actually own the largest resources of specific cryptocoins. The name of this animal comes from the characteristic fin on its back that looks like a hump. The little bump emphasizes as Cool Humpbacks raise and bend their backs in preparation for a DIP dive into the CRYPTOOCEAN to find at least ONE GEM that potentially will be providing with massive gains. The words on the reverse side of the token read: Always carry me and rub my hump for good luck.';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting is Now Open!";
const h1_public_mint = "Public Minting is Now Open!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "We're sorry. You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 😄"; 
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 😄";
const p_public_mint = "No whitelist needed. Public minting is now open! 😄";
const button_presale_coming_soon = "Get on the Whitelist!"; 
const button_presale_mint_whitelisted = "Mint Your Cool Humpback!";
const button_presale_mint_not_whitelisted = "Get on the Whitelist!";
const button_presale_already_minted = "Join Other Humpbacks! 😃";
const button_public_mint = "Mint Your Humpback";
const mint_failed = "We're Sorry, but the Minting process failed. 😢 Please try again. "; 
