const contractAddress = "0x6F328bf93C246E44beFFa966cd0E1f1a36A90412"; // Replace with your own contract address
const chain = 'goerli'; // goerli, polygon, or ethereum

const welcome_h1 = "🐳 Welcome to the Cryptoocean! 🐳 ";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'Cool Humpbacks are born from limited resources of the CRYPTOOCEAN, where they live and thrive. Collection consists of 6500 digitally generated Humpback Whales, each with various characteristics and traits, but overall with a single purpose.'
const h1_presale_coming_soon = "NFT Drop Coming Soon!";
const h1_presale_mint = "Pre-Sale Minting is Now Open!";
const h1_public_mint = "Public Minting is Now Open!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "We're sorry, but you are not whitelisted for the pre-sale..";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🐳 "; 
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🐳 ";
const p_public_mint = "No whitelist needed. Public minting is now open! 🐳 ";
const button_presale_coming_soon = "Get on the Whitelist! 🐋"; 
const button_presale_mint_whitelisted = "Mint Your Cool Humpback! 🐋";
const button_presale_mint_not_whitelisted = "Get on the Whitelist!";
const button_presale_already_minted = "Join Other Humpbacks! 🐋";
const button_public_mint = "Mint Your Cool Humpback! 🐋";
const mint_failed = "We're Sorry, but the Minting process failed. Please try again. 🐋"; 
